// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmaFlowBackend.Data;

#nullable disable

namespace PharmaFlowBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", "order_status", new[] { "pending", "confirmed", "shipped", "delivered", "cancelled", "completed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmaFlowBackend.Models.client", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<string>("billing_address")
                        .HasColumnType("text");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("delivery_address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("l_name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("last_order_date")
                        .HasColumnType("date");

                    b.Property<int?>("orders_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("id")
                        .HasName("Client_pkey");

                    b.HasIndex(new[] { "email" }, "Client_email_key")
                        .IsUnique();

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.item", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("can_be_ordered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("code_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("gtin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("official_url")
                        .HasColumnType("text");

                    b.Property<decimal?>("price_usd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ref_number")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id")
                        .HasName("Product_pkey");

                    b.HasIndex(new[] { "gtin" }, "Product_gtin_key")
                        .IsUnique();

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.lot", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<string>("certificate_url")
                        .HasColumnType("text");

                    b.Property<DateOnly>("expiration_date")
                        .HasColumnType("date");

                    b.Property<Guid>("item_id")
                        .HasColumnType("uuid");

                    b.Property<string>("lot_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("manufacture_date")
                        .HasColumnType("date");

                    b.Property<int>("quantity_available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("received_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("id")
                        .HasName("Lot_pkey");

                    b.HasIndex(new[] { "item_id", "lot_number" }, "unique_lot_per_item")
                        .IsUnique();

                    b.ToTable("lot", (string)null);
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.order", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("client_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("last_updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("order_number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("order_status")
                        .HasColumnName("status");

                    b.Property<int>("total_items")
                        .HasColumnType("integer");

                    b.Property<decimal>("total_price")
                        .HasColumnType("numeric");

                    b.HasKey("id")
                        .HasName("Order_pkey");

                    b.HasIndex("client_id");

                    b.HasIndex(new[] { "order_number" }, "Order_order_number_key")
                        .IsUnique();

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.order_lot", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("lot_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("order_lot_pkey");

                    b.HasIndex("lot_id");

                    b.HasIndex("order_id");

                    b.ToTable("order_lot", (string)null);
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.lot", b =>
                {
                    b.HasOne("PharmaFlowBackend.Models.item", "item")
                        .WithMany("lots")
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Lot_item_id_fkey");

                    b.Navigation("item");
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.order", b =>
                {
                    b.HasOne("PharmaFlowBackend.Models.client", "client")
                        .WithMany("orders")
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Order_client_id_fkey");

                    b.Navigation("client");
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.order_lot", b =>
                {
                    b.HasOne("PharmaFlowBackend.Models.lot", "lot")
                        .WithMany("order_lots")
                        .HasForeignKey("lot_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("order_lot_ot_id_fkey");

                    b.HasOne("PharmaFlowBackend.Models.order", "order")
                        .WithMany("order_lots")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_lot_order_id_fkey");

                    b.Navigation("lot");

                    b.Navigation("order");
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.client", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.item", b =>
                {
                    b.Navigation("lots");
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.lot", b =>
                {
                    b.Navigation("order_lots");
                });

            modelBuilder.Entity("PharmaFlowBackend.Models.order", b =>
                {
                    b.Navigation("order_lots");
                });
#pragma warning restore 612, 618
        }
    }
}
